### ISSUE TITLE
列过多时无横向滚动条 右侧列直接看不到。

### ISSUE THREAD

**Issue by treefung** [kaysonli/v-fit-columns#1]
作者思路可以 我尝试过若干扩展，都不太理想

我加入了 解决了不出现滚动条

.el-table__body-wrapper {
  overflow: auto;
}

**Comment by kaysonli** [comment]
> 作者思路可以 我尝试过若干扩展，都不太理想
> 
> 我加入了 解决了不出现滚动条
> 
> .el-table__body-wrapper {
> overflow: auto;
> }

我自己项目里是加了的，忘了放进这个插件了。已修改，谢谢指出。
